// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7vSccSCqXRHYn5JaTo_6RZsamCdc8wKY',
    appId: '1:391423906647:web:97adf53b95a9e426b56412',
    messagingSenderId: '391423906647',
    projectId: 'todo-app-new-fb1f0',
    authDomain: 'todo-app-new-fb1f0.firebaseapp.com',
    storageBucket: 'todo-app-new-fb1f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmE9LS5OmKUFFJBr7EJMytK3kyq5WNT8',
    appId: '1:391423906647:android:49bfc623901b30f2b56412',
    messagingSenderId: '391423906647',
    projectId: 'todo-app-new-fb1f0',
    storageBucket: 'todo-app-new-fb1f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXyoUjPNwj-g88V5OsRh7QV8scgdT4U_o',
    appId: '1:391423906647:ios:cbc075c3c51ce431b56412',
    messagingSenderId: '391423906647',
    projectId: 'todo-app-new-fb1f0',
    storageBucket: 'todo-app-new-fb1f0.firebasestorage.app',
    iosBundleId: 'com.example.toDoMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXyoUjPNwj-g88V5OsRh7QV8scgdT4U_o',
    appId: '1:391423906647:ios:cbc075c3c51ce431b56412',
    messagingSenderId: '391423906647',
    projectId: 'todo-app-new-fb1f0',
    storageBucket: 'todo-app-new-fb1f0.firebasestorage.app',
    iosBundleId: 'com.example.toDoMachineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7vSccSCqXRHYn5JaTo_6RZsamCdc8wKY',
    appId: '1:391423906647:web:468da210819db69fb56412',
    messagingSenderId: '391423906647',
    projectId: 'todo-app-new-fb1f0',
    authDomain: 'todo-app-new-fb1f0.firebaseapp.com',
    storageBucket: 'todo-app-new-fb1f0.firebasestorage.app',
  );
}
